import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import Provider from "@/lib/Provider";
export const metadata = {
  title: "Menu Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
